---
name: example_rule
enabled: true
description: "Example rule"
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "example"
criteria: {}
action:
  ref: example_pack.example_action
  description: Service remediations in StackStorm with ssh
  parameters:
    rhost: "{{ trigger.body.result.host }}"
    host: "{{ trigger.body.host }}"
